config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :authors

  namespace :authors do
    resources :posts do
      resources :elements
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed'] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: %i[update destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join('. ')
      end

      redirect_to edit_authors_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_authors_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_authors_post_path(@element.post)
    end

    private

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors

  class PostsController < AuthorsController
    before_action :set_post, only: %i[ show edit update destroy ]

    def index
      @posts = current_author.posts.all
    end

    # GET /authors/posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /authors/posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /authors/posts
    # POST /authors/posts.json
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to authors_posts_path, notice: 'Post was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /authors/posts/1
    # PATCH/PUT /authors/posts/1.json
    def update
      if @post.update(post_params)
        redirect_to [:authors, @post], notice: 'Post was successfully updated.'
        head :no_content
      else
        render action: 'edit'
        render json: @post.errors, status: :unprocessable_entity
      end
    end

    # DELETE /authors/posts/1
    # DELETE /authors/posts/1.json
    def destroy
      @post.destroy

      redirect_to authors_posts_url, notice: 'Post was successfully destroyed.'
      head :no_content
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ActionController::Base
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<!-- app/views/authors/posts/_form.html.erb -->
<%= form_for([:authors, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to 'Back', authors_posts_path, class: 'btn btn-secondary mb-3' %>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title w-100">Editing Post</h4>
        <%= render 'form' %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="mb-3">
      <div class="d-flex flex-row">
        <%= form_with(model: [:authors, @post, @element], html: { class: "mr-1" }) do |form| %>
          <%= form.hidden_field :element_type, value: 'paragraph' %>
          <%= form.submit "Paragraph", class: 'btn btn-dark' %>
        <% end %>
        <%= form_with(model: [:authors, @post, @element]) do |form| %>
          <%= form.hidden_field :element_type, value: 'image' %>
          <%= form.submit "Image", class: 'btn btn-dark' %>
        <% end %>
      </div>
    </div>
    <div class="card">
      <div class="card-body pt-5">
        <% @post.elements.each do |element| %>
          <% if element.persisted? %>
            <% if element.paragraph? %>
              <div class="mb-4 p-3 paragraph">
                <div class="paragraph-content">
                  <% if element.content.present? %>
                    <%= element.content %>
                  <% else %>
                    Click to add content.
                  <% end %>
                </div>
                <div class="paragraph-form d-none">
                  <%= form_with(model: [:authors, @post, element]) do |form| %>
                    <%= form.rich_text_area :content %>
                    <div class="mt-3 d-flex justify-content-between">
                      <div>
                        <%= form.submit "Save", class: 'btn btn-primary' %>
                        <a href="#" class="cancel btn btn-secondary">Cancel</a>
                      </div>
                      <%= link_to "Delete", authors_post_element_path(@post, element), 
                        class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% elsif element.image? %>
              <div class="mb-4 p-3 image">
                <% if element.image.present? %>
                  <%= image_tag(element.image) %>
                <% else %>
                  <%= form_with(model: [:authors, @post, element]) do |form| %>
                    <%= form.file_field :image %>
                    <div class="mt-3">
                      <%= form.submit "Save", class: 'btn btn-primary' %>
                      <a href="#" class="cancel btn btn-secondary">Cancel</a>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end%>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/authors/posts/index.html.erb
<!-- app/views/authors/posts/index.html.erb -->
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary' %>  
</h4>
<% @posts.each do |post| %>
  <%= link_to edit_authors_post_path(post), class: 'text-decoration-none' do %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title text-dark mb-1"> <%= post.title %> </h5>
        <p class="text-secondary mb-0"> <%= post.description %> </p>
        <%= link_to 'Destroy', [:authors, post], :method => :delete, :data => { :confirm => 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>
<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/show.html.haml
%p
  %b Title:
  = @post.title
%p
  %b Content:
  = @post.content
%p
  %b Published:
  = @post.published

= link_to 'Edit', edit_authors_post_path(@post)
\|
= link_to 'Back', authors_posts_path

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track" => "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>BlogSensu - Authors</title>
    <meta content="width=device-width,initial-scale=1" name="viewport"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>

    <%= stylesheet_link_tag "authors", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "authors", "data-turbo-track": "reload" %>
    <%# <script type="module" data-turbo-track="reload">
      import railsActiontext from 'https://cdn.skypack.dev/@rails/actiontext';
    </script>
    %>
    <script type="module" data-turbo-track="reload">
      import trix from 'https://cdn.skypack.dev/trix';
    </script>
    <%# <%= javascript_importmap_tags %>
  </head>
  <body class="sidebar-mini layout-fixed authors" style="height: auto;">
    <div class="wrapper">
      <%= render partial: "/layouts/partials/authors/header" %>
    </div>
    <div class="wrapper">
      <%= render partial: "/layouts/partials/authors/sidebar" %>
      <div class="content-wrapper">
        <%= render partial: "/layouts/partials/authors/page_header" %>
        <div class="content">
          <div class="container-fluid">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>

            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: "/layouts/partials/authors/footer" %>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<div class="b-example-divider"></div>
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1" href="/">
        <svg class="bi" height="24" width="30">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>
      <span class="text-muted">
        cia
      </span>
    </div>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3">
        <a class="text-muted social-network twitter" href="#">
          <i></i>
        </a>
      </li>
      <li class="ms-3">
        <a class="text-muted social-network facebook" href="#">
          <i></i>
        </a>
      </li>
      <li class="ms-3">
        <a class="text-muted social-network instagram" href="#">
          <i></i>
        </a>
      </li>
    </ul>
  </footer>
</div>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#!">Start Bootstrap</a>
    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#!">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#!">Contact</a>
        </li>
        <li class="nav-item">
          <a aria-current="page" class="nav-link active" href="#">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/partials/_sidebar.html.erb
<!-- Search widget
-->
<div class="card mb-4">
  <div class="card-header">Search bar</div>
  <div class="card-body">
    <div class="input-group">
      <input aria-describedby="button-search" aria-label="Enter search term..." class="form-control" placeholder="Enter search term..." type="text">/</input>
      <button class="btn btn-primary" id="button-search" type="button">Go!</button>
    </div>
  </div>
</div>
<!-- Categories widget
-->
<div class="card mb-4">
  <div class="card-header">Categories</div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!">Web Design</a>
          </li>
          <li>
            <a href="#!">HTML</a>
          </li>
          <li>
            <a href="#!">Freebies</a>
          </li>
        </ul>
      </div>
      <div class="col-sm-6">
        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!">JavaScript</a>
          </li>
          <li>
            <a href="#!">CSS</a>
          </li>
          <li>
            <a href="#!">Tutorials</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Side widget
-->
<div class="card mb-4">
  <div class="card-header">Side Widget</div>
  <div class="card-body">
    You can put anything you want inside of these side widgets. They are easy to use, and
    feature the Bootstrap 5 card component!
  </div>
</div>

app/views/layouts/partials/authors/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2022 <a href="http://localhost:3000">site.com</a>.</strong>
  Direitos Resrvados.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 0.0.1
  </div>
</footer>

app/views/layouts/partials/authors/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/layouts/partials/authors/_page_header.html.erb
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->